### ISSUE TITLE
Error when uploading finger

### ISSUE THREAD

**Issue by Mayavan** [vinaychandraka/Fingerprint_module_R305---Python_and_MySQL#1]
Traceback (most recent call last):
  File "C:/Users/PyCharm/FingerPrintUpload.py", line 145, in <module>
    if UpChar(2):
  File "C:/Users/PyCharm/FingerPrintUpload.py", line 98, in UpChar
    s = readPacket1()
  File "C:/Users/PyCharm/FingerPrintUpload.py", line 53, in readPacket1
    ret1.extend(struct.unpack(form1, v))
struct.error: unpack requires a string argument of length 688

**Comment by Devrajath** [comment]
Program is up and running well with Ubuntu 16.04;  can you put some screenshot over here.
Regards,
Rajath Kumar K S
