### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by Veneth** [vinaychandraka/Fingerprint_module_R305---Python_and_MySQL#4]
Dear Vinaychandraka,

While running your code on raspberry pi3 I get this error. Please help me to fix that error!

```
Type done to exit
Enter name : veneth

Traceback (most recent call last):
  File "/home/pi/Veneth/R305/upload fingerprint.py", line 92, in <module>
    if verifyFinger():
  File "/home/pi/Veneth/R305/upload fingerprint.py", line 63, in verifyFinger
    return s[4]
IndexError: list index out of range
```

**Comment by douglaskorgut** [comment]
File "1_upload_template.py", line 162, in <module>
    if verifyFinger():              # if password is correct zero gets returned , else a non zero value (13H) gets returned and 'Verification Error' gets printed
  File "1_upload_template.py", line 126, in verifyFinger
    return s[4]
IndexError: list index out of range



Same thing here
