### ISSUE TITLE
out of range

### ISSUE THREAD

**Issue by OrbisTerrarumProLiberi** [vinaychandraka/Fingerprint_module_R305---Python_and_MySQL#9]
Enter name : test
Traceback (most recent call last):
  File "dbupload.py", line 90, in <module>
    if verifyFinger():
  File "dbupload.py", line 61, in verifyFinger
    return s[4]
IndexError: list index out of range

**Comment by broyusop** [comment]
`enter the name please: yusop
enter the store id: 2
Traceback (most recent call last):
  File "fingerDownload.py", line 80, in <module>
    if verifyFinger():              # Verify Password
  File "fingerDownload.py", line 65, in verifyFinger
    return s[4]
IndexError: list index out of range

same with mine, any help???`
